#!/usr/bin/env sh

# NAME
#  nvim-config-i3-widget
#
# DESCRIPTION
#  Get the current NVim config, the symlinked folder that ~/.config/nvim 
#  points to.
#  This script is meant to be used with the i3blocks status bar.
#
#  When the widget is clicked, it allows the user to switch between
#  NVim configs. 
#
# SEE ALSO
#  nvim-config(1)

case "$BLOCK_BUTTON" in
  # Left click
	1) nvim-config change > /dev/null 2>&1 & ;;
esac

nvim-config

