#!/usr/bin/env dash

# NAME
#  die - Function to print an error message and exit with a non-zero code
#
# SYNOPSIS
#  die <message> [code]
#
# DESCRIPTION
#  Prints an error message and exits with a non-zero code. If the DISPLAY
#  variable is set, a graphical error message is shown via doomst, a doomguy 
#  icon themed dunst notification. Otherwise, the error message is printed to
#  stderr.
#
# SEE ALSO
#  doomst(1)

die() {
  script_name=$(basename "$0")
  message="$1"

  if [ -n "$DISPLAY" ]; then
    doomst --title "$script_name" --message "$message" --type error
  fi

  formatted_messages=$(echo "$message" \
    | sed 's/\\n/\n/g' \
    | sed 's/<u>/\x1b[4m/g' \
    | sed 's/<\/u>/\x1b[0m/g' \
  )

  echo "[${script_name}][$(red "error")] ${formatted_messages}" 1>&2

  exit "${2:-1}"
}

