#!/usr/bin/env dash

# Check if the script is being sourced or not. It should only be sourced.
guard_is_sourced() {
  if [ "${0##*/}" = "sh" ] || [ "${0##*/}" = "bash" ]; then
    echo "This script should be sourced, not executed."
    exit 1
  fi
}
