#!/usr/bin/sh

# Checks if a command exists in the system.
does_command_exist() {
  for command in "$@"; do 
    if ! command -v "$command" >/dev/null 2>&1; then
      echo "Error: Required command '$command' is not installed." >&2
      return 1
    fi
  done
}
