#!/usr/bin/sh

hour=$(date '+%I')

case "$hour" in
	"00") icon="🕛" ;;
	"01") icon="🕐" ;;
	"02") icon="🕑" ;;
	"03") icon="🕒" ;;
	"04") icon="🕓" ;;
	"05") icon="🕔" ;;
	"06") icon="🕕" ;;
	"07") icon="🕖" ;;
	"08") icon="🕗" ;;
	"09") icon="🕘" ;;
	"10") icon="🕙" ;;
	"11") icon="🕚" ;;
	"12") icon="🕛" ;;
esac

case "$BLOCK_BUTTON" in
  # Left click
	1) 
    cal2Months=$(cal --color=always -n 2 \
      | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/" \
    )

    doomst --title " Calendar" --message "$cal2Months"
  ;;
esac

day=$(date +%-e)

case $day in
  1?) day=${day}th ;;
  1|21|31) day=${day}st ;;
  2|22) day=${day}nd ;;
  3|23) day=${day}rd ;;
  *) day=${day}th ;;
esac

printf '%s %s\n' "$icon" "$(date "+$day %B %Y :: %T ")" 
