#!/usr/bin/sh

case "$BLOCK_BUTTON" in
  # Left click
  1) st newsboat ;;

  # Middle click
  2) ;;

  # Right click
	3) ;;

  # Scroll up
  4) ;;

  # Scroll down
  5) ;;
esac

unreadCount=$(newsboat -x print-unread | awk '{print $1}')

# When undefined, a raw format is assumed. Each line of the output corresponds
# to an i3bar key, in the order of definition found in the i3bar protocol:
# 
# - 1st line: full_text
# - 2nd: short_text
# - 3rd: text color
# - 4th: background

echo "$unreadCount unread"
echo "$unreadCount"

if [ $unreadCount -gt 0 ]; then
  echo "#fabd2f"
fi
