#!/usr/bin/sh

case "$BLOCK_BUTTON" in
  # Left click
  1) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;

  # Middle click
  2) ;;

  # Right click
	3) st pacmixer ;;

  # Scroll up, increase volume
  4) pactl set-sink-volume @DEFAULT_SINK@ +5% ;;

  # Scroll down, decrease volume
  5) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
esac

SINK=$(pacmd list-sinks | \
  grep "* index:" --after 11 | \
  grep "index:\|name:\|volume: \(front\|mono\)\|muted:")
VOLUME=$(echo "$SINK" | \
  grep "volume:" | \
  awk '{print $5}')
IS_MUTED=$(echo "$SINK" | \
  grep "muted:" | \
  awk '{print $2}')

case "$IS_MUTED" in
  "yes")
    echo "婢 $VOLUME"
    exit 33
    ;;
  "no")
    echo " $VOLUME"
    ;;
esac
