#!/usr/bin/env sh

. "$FCLI_FUNCTIONS/stdin-or"

export LOG_NAMESPACE="󱅄 writing"
export LOG_LEVEL=info

# NAME
#  bookmarks - Manage bookmarks
#
# SYNOPSIS
#  bookmarks [COMMAND]
#
# DESCRIPTION
#  Bookmarks are individual .toml files stored in $BOOKMARKS_DATA.
#  This script provides a CRUD interface for managing bookmarks.
#
# COMMANDS
# list
#  List all bookmarks
# open
#  Open a bookmark in the default browser
# upsert
#  Create or edit a bookmark
#
# SEE ALSO

get_toml_field() {
  input=$(cat)
  field_name="$1"

  fancy-log info -v field_name "$field_name" -v "1" "$1" -v input "$input"

  echo "$input" \
    | grep "^$field_name=" \
    | sed 's/^[^=]*=//; s/^"//; s/"$//'
}

list() {
  rg --files --glob '**/*' \
    --sortr modified \
    "$BOOKMARKS_DATA"
}

# Open Nvim with the bookmark file. If the file does not exist, create it 
# applying a template.
open_or_create() {
  path="$1"

  if [ ! -f "$path" ]; then
    path="$BOOKMARKS_DATA/$path.toml"

    {
      echo "id=\"$(random uuid)\""
      echo "url=\"\""
      echo "title=\"\""
      echo "author=\"\""
      echo "tags=[\"linux\"]"
      echo "type=\"article|library|video|documentation\""
      echo "created_at=\"$(date --iso-8601=seconds)\""
      echo ""
    } > "$path"
  fi

  # Set nvim's NerdTree file explorer to the snippets directory
  cd "$BOOKMARKS_DATA"

  nvim \
    -c "norm zz" \
    -c "set spell" \
    -c "set syntax=markdown" \
    "$path"
}

# Choose a bookmark from the list of all bookmarks. If no bookmark is found 
# for the user's query, return the query.
choose() {
  title="$1"
  delimiter_count=$(echo "$BOOKMARKS_DATA" \
    | grep --only-matching "/" \
    | wc --lines
  ) 
  all_bookmarks=$(list)
  choice=$(echo "$all_bookmarks" \
    | fzf \
      --preview 'bat --color=always --style=numbers --line-range :500 {}' \
      --preview-window=right:85:wrap \
      --header "$title" \
      --delimiter "/" \
      --with-nth=$(( delimiter_count + 2 )) \
      --print-query
    )
  query=$(echo "$choice" | head -n 1)
  bookmark_path=$(echo "$choice" | tail -n 1)

  if [ -z "$bookmark_path" ]; then
    echo "$query"
  else
    echo "$bookmark_path"
  fi
}

case ${1:-open} in
  list) 
    list
  ;;
  open)
    path=$(choose " open bookmark:")

    if [ -f "$path" ]; then
      url=$(get_toml_field "url" < "$path")

      if [ -z "$url" ]; then
        fancy-log error -v field "url" -v file "$path" "Field not found"
      else
        xdg-open "$url" &
      fi
    fi
  ;;
  upsert)
    path=$(choose "󱄀 edit or create bookmark:")

    if [ -z "$path" ]; then 
      fancy-log info "No bookmark selected, bye bye!"
    elif open_or_create "$path"; then
      fancy-log success -v path "$path" "Bookmark saved"
    fi
  ;;
  *) 
    fancy-log error \
      -v cmd "$1" \
      -v available_commands "list,open,upsert" \
      "Command not found"
    exit 1 
  ;;
esac
