#!/bin/sh -eu

# absolute path of the folder containing this script file
dirpath=$(dirname "$(realpath "$0")")

#
# Restore nvim configs
#

mkdir -p "$HOME/.config"
cp -r "$dirpath/.config/sway" "$HOME/.config"
cp -r "$dirpath/.config/i3blocks" "$HOME/.config"
cp -r "$dirpath/.config/dunst" "$HOME/.config"
cp -r "$dirpath/.config/rofi" "$HOME/.config"

#
# Install graphics related packages
#

sudo pacman --noconfirm -S \
  imagemagick \
  imv \
  xorg-xlsclients \
  xorg-xwayland \
  mesa \
  grim \
  slurp
