#!/bin/sh -eu

# absolute path of the folder containing this script file
dirpath=$(dirname "$(realpath "$0")")

#
# Restore configs
#

echo "// Restore 'fontconfig' into '~/.config'"

mkdir -p "$HOME/.config"
cp -r "$dirpath/.config/fontconfig" "$HOME/.config"

echo "// Copy font into '.local/share/fonts'"

mkdir -p "$HOME/.local/share/fonts"
cp -r "$dirpath/.local/share/fonts" "$HOME/.local/share"
