#!/bin/sh

# Exit script if any statement returns a non-true return value
set -e

# Exit script if trying to use an uninitialised variable
set -u

# absolute path of the folder containing this script file
dirpath=$(dirname "$(realpath "$0")")

sudo pacman --noconfirm -S \
  signal-desktop \
  firefox-developer-edition

aur rofi-lbonn-wayland-git
aur pacmixer
