#!/bin/sh

# Exit script if any statement returns a non-true return value
set -e

# Exit script if trying to use an uninitialised variable
set -u

# absolute path of the folder containing this script file
dirpath=$(dirname "$(realpath "$0")")

#
# Restore nvim configs
#

mkdir -p "$HOME/.config"
cp -r "$dirpath/.config/sway" "$HOME/.config"
cp -r "$dirpath/.config/i3blocks" "$HOME/.config"
cp -r "$dirpath/.config/dunst" "$HOME/.config"
cp -r "$dirpath/.config/rofi" "$HOME/.config"

#
# Install graphics related packages
#

sudo pacman --noconfirm -S \
  imagemagick \
  dunst \
  imv \
  rofi \
  ffmpeg \
  xorg-xlsclients \
  xorg-xwayland \
  wayland \
  qt5-wayland \
  glfw-wayland \
  wl-clipboard \
  mesa \
  sway \
  swaylock \
  swayidle \
  waybar \
  grim \
  slurp
