#!/bin/sh

# absolute path of the folder containing this script file
dirpath=$(dirname "$(realpath "$0")")

#
# Main folders
#

mkdir -p "$HOME/Downloads"
mkdir -p "$HOME/Pictures/Wallpapers"
mkdir -p "$HOME/Pictures/Screenshots"
mkdir -p "$HOME/Work"
mkdir -p "$HOME/Media"

#
# Restore configs
#

echo "#"
echo "# - Restore 'fontconfig' into '~/.config'"
echo "# - Copy font into '.local/share/fonts'"
echo "#"

cp -r "$dirpath/.config/mimeapps.list" "$HOME/.config"
cp -r "$dirpath/.config/alacritty" "$HOME/.config"
cp -r "$dirpath/home/.gitconfig" "$HOME/"
cp -r "$dirpath/home/.profile" "$HOME/"
cp -r "$dirpath/doomguy.png" "$HOME/"
cp -r "$dirpath/doomguy-blood.png" "$HOME/"
cp -r $dirpath/wallpapers/* "$HOME/Pictures/Wallpapers"

#
# Enable 'extra' and 'community' Arch repos
#

echo "#"
echo "# Enable 'extra' and 'community' Arch repos"
echo "#"

# Update package database
sudo pacman -Syy

# Allow arch repos
sudo pacman -S artix-archlinux-support

if grep -q "^\[extra\]$" /etc/pacman.conf; then
  echo "[extra] already enabled"
else
  echo "[extra]" >> /etc/pacman.conf
  echo "Include = /etc/pacman.d/mirrorlist-arch" >> /etc/pacman.conf
fi

if grep -q "^\[community\]$" /etc/pacman.conf; then
  echo "[community] already enabled"
else
  echo "[community]" >> /etc/pacman.conf
  echo "Include = /etc/pacman.d/mirrorlist-arch" >> /etc/pacman.conf
fi

sudo pacman-key --populate archlinux

#
# Install packages
#

sudo pacman --noconfirm -S \
  cronie \
  cronie-runit \
  openssh \
  keychain \
  libsecret \
  rsync \
  git-delta \
  fzf \
  the_silver_searcher \
  bat \
  ripgrep \
  nnn \
  htop \
  neofetch \
  nnn \
  unzip \
  xdg-desktop-portal-wlr \
  alacritty \
  bluez \
  bluez-utils \
  bluez-runit \
  pulseaudio-bluetooth

sudo ln -s /etc/runit/sv/bluetoothd /run/runit/service
sudo sv start bluetoothd
