#!/bin/sh -eu

# absolute path of the folder containing this script file
dirpath=$(dirname "$(realpath "$0")")

#
# Restore nvim configs
#

mkdir -p "$HOME/.config"
cp -r "$dirpath/.config/nvim" "$HOME/.config"

# 
# Install vim-plug
#

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
