#!/bin/sh

# Exit script if any statement returns a non-true return value
set -e

# Exit script if trying to use an uninitialised variable
set -u

# absolute path of the folder containing this script file
dirpath=$(dirname "$(realpath "$0")")

#
# Restore configs
#

echo "// Restore 'fontconfig' into '~/.config'"

mkdir -p "$HOME/.config"
cp -r "$dirpath/.config/fontconfig" "$HOME/.config"

echo "// Copy font into '.local/share/fonts'"

mkdir -p "$HOME/.local/share/fonts"
cp -r "$dirpath/.local/share/fonts" "$HOME/.local/share"

echo "// Install font packages - fontconfig noto-fonts zathura zathura-pdf-mupdf"

sudo pacman --noconfirm -S \
  fontconfig \
  zathura \
  zathura-pdf-mupdf \
  ttf-liberation \
  noto-fonts \
  gnu-free-fonts
