#!/bin/sh -eu

# absolute dir path of this script file
dirpath=$(dirname "$(realpath "$0")")

echo "###############################################"
echo "# Install 'git' to clone dotfiles"
echo "###############################################"

sudo pacman --noconfirm -S git

dotfile_home="$HOME/Work/andreidmt/dotfiles"
git clone git@github.com:andreidmt/dotfiles.git "$dotfile_home"

echo "###############################################"
echo "# Create core directories"
echo "###############################################"

mkdir -p "$HOME/Downloads"
mkdir -p "$HOME/Media"
mkdir -p "$HOME/Backups"
mkdir -p "$HOME/Pictures/Wallpapers"
mkdir -p "$HOME/Pictures/Screenshots"
mkdir -p "$HOME/Work/asd14"

