#!/usr/bin/env dash

# DESCRIPTION
#  Show a calendar for the current and next month as a dunst notification.
#  This script is meant to be used with `polybar`.

convert_ansi_to_pango() {
  sed -e 's/\x1b\[0m/<\/span>/g' \
      -e 's/\x1b\[1;41m/<span background="red">/g' \
      -e 's/\x1b\[35m/<span foreground="magenta">/g' \
      -e 's/\x1b\[33m/<span foreground="yellow">/g' \
      -e 's/\x1b\[1;33m/<span foreground="yellow">/g'
}

two_months=$(cal --color=always --months 2 --monday --week \
  | convert_ansi_to_pango)

doomst --title " Calendar" --message "$two_months" --expire-time 0

