#!/usr/bin/env sh

# shellcheck source=../../../@0_fancy-posix-utils/functions/predicates
. "$FCLI_FUNCTIONS/predicates"

# DESCRIPTION
#  Start `dunst` if it is not already running.
# 
# ERROR CODES
#  1 Xorg is not running
#
# SEE ALSO
#  polybar(1)

if ! is_process_running "Xorg"; then
  exit 1
fi

if ! is_process_running "dunst"; then
  dunst &
fi

