#!/usr/bin/sh

# NAME
#  sys-lock - Fancyfy swaylock with blured bg images and system level theme
#
# DESCRIPTION
#  Take screenshots of all available displays, blur them, 
#  and set them as background images for the screen locker.
#
# SYNOPSIS
#  sys-lock
#
# ENVIRONMENT
#   SYS_COLOR_* - Exposed by sys-theme
#
# FILES
#   /tmp/lockscreen-*.png - Temporary screenshot files for each display
#
# SEE ALSO
#  sway(1), swaylock(1), sys-theme(1), grim(1), magick(1), jq(1), fancy-log(1)

BLUR_TYPE="0x8"
DISPLAYS=$(swaymsg -t get_outputs | jq -r '.[].name')

# Ensure required dependencies are available
for cmd in grim magick swaylock jq swaymsg; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    fancy-log error -v name "$cmd" "Required dependency not found"
    exit 1
  fi
done

# Take a screenshots for each display
SWAYLOCK_IMAGE_ARG=""
for display in $DISPLAYS; do
  tmp_path="/tmp/lockscreen-$display.png"
  grim -o "$display" "$tmp_path"
  magick "$tmp_path" -blur $BLUR_TYPE "$tmp_path"
  SWAYLOCK_IMAGE_ARG="$SWAYLOCK_IMAGE_ARG --image $display:$tmp_path"
done

swaylock --daemonize \
  $SWAYLOCK_IMAGE_ARG \
  --font monospace \
  --font-size 20 \
  --show-keyboard-layout \
  --show-failed-attempts \
  --line-uses-ring \
  --indicator-caps-lock \
  --indicator-radius 100 \
  --indicator-thickness 15 \
  --layout-bg-color "$SYS_COLOR_BG" \
  --layout-text-color "$SYS_COLOR_FG" \
  --ring-color "$SYS_COLOR_BG" \
  --ring-caps-lock-color "$SYS_COLOR_BG" \
  --key-hl-color "$SYS_COLOR_GREEN_DARK" \
  --caps-lock-key-hl-color "$SYS_COLOR_GREEN_DARK" \
  --bs-hl-color "$SYS_COLOR_RED_DARK" \
  --caps-lock-bs-hl-color "$SYS_COLOR_RED_DARK" \
  --inside-color "$SYS_COLOR_BG" \
  --inside-caps-lock-color "$SYS_COLOR_BG" \
  --separator-color 00000000 \
  --text-color "$SYS_COLOR_FG" \
  --ring-wrong-color "$SYS_COLOR_RED_DARK" \
  --inside-wrong-color "$SYS_COLOR_BG" \
  --text-wrong-color "$SYS_COLOR_FG" \
  --ring-ver-color "$SYS_COLOR_BLUE_DARK" \
  --inside-ver-color "$SYS_COLOR_BG" \
  --text-ver-color "$SYS_COLOR_FG" \
  --ring-clear-color "$SYS_COLOR_YELLOW_DARK" \
  --inside-clear-color "$SYS_COLOR_BG" \
  --text-clear-color "$SYS_COLOR_FG"

