#!/usr/bin/env bash

plugins=(
  # Replace zsh's default completion selection menu with fzf! 
  "Aloxaf/fzf-tab"
  # ZSH_SYNTAX
  "zsh-users/zsh-syntax-highlighting"
  # ZSH_SUGGESTIONS
  "zsh-users/zsh-autosuggestions"
  # nvm can be kind of a pain to install and keep up to date. This zsh plugin
  # allows you to quickly setup nvm once then never worry about it again.
  "lukechilds/zsh-nvm"
  # A better npm completion script for ZSH
  # - Makes npm install recommendations from npm cache
  # - Makes npm uninstall recommendations from dependencies/devDependencies
  # - Shows detailed information on script contents for npm run
  # - Falls back to default npm completions if we don't have anything better
  "lukechilds/zsh-better-npm-completion"
  # Implementation Fish shell's history search feature, where you can type in
  # any part of any command from history and cycle through the matches.
  "zsh-users/zsh-history-substring-search"
)

mkdir -v -p "$ZSH_PLUGIN_HOME"

for gitAddress in "${plugins[@]}"; do
  local pluginName="$(basename "$gitAddress")"
  local pluginPath="$ZSH_PLUGIN_HOME/$pluginName"

  if [ -d "$pluginPath" ]; then
    echo "Plugin already exists. Updating..."
    cd "$pluginPath" && git pull
  else 
    git clone --depth 1 "https://github.com/$gitAddress" "$pluginPath"
  fi
done
