#!/bin/sh

while read file
do
    case "$1" in
    # Set wallpaper
    "w") fish -c "wall \"$file\"" & ;;

    #
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	
    #
    "Y")
		echo -n "$(readlink -f "$file")" | xclip -selection clipboard &&
		notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	
    # Delete file via rofi confirm
    "d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
    
    # Open with Gimp
    "g")
        gimp "$file" & ;;
    esac
done
