#!/usr/bin/env dash

# DESCRIPTION
#  Show the number of packages that can be upgraded.
#  This script is meant to be used with `polybar`.

package_count=$(pacman -Qu | wc -l)

if [ "$package_count" -gt 10 ]; then
  red=$(xrdb -query | grep "color1:" | awk '{print $NF}')
  echo "%{B$red}$package_count packages%{B-}"
else
  echo "$package_count packages"
fi
