#!/usr/bin/env sh

# i3 thread: https://faq.i3wm.org/question/150/how-to-launch-a-terminal-from-here/?answer=152#post-id-152

cwd=''
windowId=$(xdpyinfo | grep focus | cut -f4 -d " ")
processId=$(xprop -id "$windowId" | grep -m 1 PID | cut -d " " -f 3)

# Last child process (shell, vim, etc)
if [ -n "$processId" ]; then
  TREE=$(pstree -lpA "$processId" | tail -n 1)
  processId=$(echo "$TREE" | awk -F'---' '{print $NF}' | sed -re 's/[^0-9]//g')

  # If we find the working directory, run the command in that directory
  if [ -e "/proc/$processId/cwd" ]; then
    cwd=$(readlink "/proc/$processId/cwd")
  fi
fi

if [ -n "$cwd" ]; then
  cd "$cwd" && $TERMINAL
else
  $TERMINAL
fi
