#!/usr/bin/env dash

# NAME
#  nano_to_s - Convert nanoseconds to seconds
#
# SYNOPSIS
#  nano_to_s <nanoseconds> [decimal_places]
#
# DESCRIPTION
#   Converts a value from nanoseconds to seconds. If 'decimal_places'
#   is not specified, it defaults to 2.
#
# ARGUMENTS
#   <nanoseconds>      The number of nanoseconds to convert.
#   [decimal_places]   Number of decimal places in the result (default: 2).
#
# SEE ALSO
#  bc(1)

nanoseconds=$1
decimal_places=${2:-2}

result=$(echo "scale=$decimal_places; $nanoseconds / 1000000000" | bc -l)

# Prepend 0 if result starts with a dot
case "$result" in
  .*) result="0$result" ;;
esac

echo "$result"

