#!/bin/bash

CMD=${1:-restart}

function lemonbarStart {
    screenWidth=$(xrandr --query | awk '/\<current\>/{print $8}')-60
    barWidth=$(( screenWidth-60 ))

    lemon__main | lemonbar -p -f mono -f icons -B $BACKGROUND -g ${barWidth}x40+60+10 -d &
}

if [ $CMD == "toggle" ]; then
    if pgrep -x lemonbar >/dev/null
    then
        pkill -9 lemonbar
    else
        lemonbarStart
    fi
fi

if [ $CMD == "restart" ]; then
    pkill -9 lemonbar
    lemonbarStart
fi
