#!/usr/bin/env sh

# NAME
#  ai-model-i3-widget
#
# DESCRIPTION
#  Get the current OpenAI model. This script is meant to be used with the 
#  i3blocks status bar.
#
#  When the widget is clicked, it runs "ai-model change", which opens a
#  rofi menu with all the available OpenAI models.
#
# SEE ALSO
#  ai-choose-model(1)

case "$BLOCK_BUTTON" in
  # Left click
	1) ai-model change ;;
esac

ai-model
