#!/usr/bin/env sh

# NAME
#  ai-history - List all OpenAI conversation, completion or chat logs
#
# SYNOPSIS
#  ai-history
#
# DESCRIPTION
#  List all Conversations 
#
# SEE ALSO
#  fzf(1)

conversation_id="$1"

if [ -z "$conversation_id" ]; then
  conversation_id=$(
    ai-db-find-many -t Conversations \
    | jq --raw-output '.[] | "\(.id)::\(.title) (\(.messages_count))"' \
    | fzf \
    --delimiter "::" \
    --with-nth "2" \
    --print-query \
    --header "$OPENAI_ICON Select a conversation to resume:" \
    --preview 'ai-recall {1}' \
    --preview-window 'right:60%:wrap' \
    | awk -F "::" '{print $1}'
  )
fi

ai-recall "$conversation_id"
