#!/usr/bin/env sh

# Predicate checking if a process is running under the current user
is_process_running() {
  name=$1
  args=$2

  if [ -z "$args" ]; then
    pgrep "$name" -u "$USER" > /dev/null
  else
    pgrep --full "$name $args" -u "$USER" > /dev/null
  fi
}

# Predicate checking if a command exists
does_command_exist() {
  if ! command -v "$1" >/dev/null 2>&1; then
    return 1
  fi
}
