#!/usr/bin/env sh

# NAME
#  cron_camerashot - Take a screenshot from a webcam
#
# DESCRIPTION
#  This script is meant to be run by cron. It checks if the screen is locked and
#  if not, it takes a screenshot from the webcam and saves it to a file.

export SCREEN_HOME="/home/andreid/Work/andreidmt.dotfiles/new/modules/screen"
export SCREEN_TMP="$SCREEN_HOME/.tmp"

$SCREEN_HOME/scripts/camerashot \
  -o "$SCREEN_HOME/.local/time-lapse/$(date +"%Y-%m-%d")"
