#!/bin/sh

exec 2>&1

# The script must be run as root because it uses "mount" and "umount" which
# requires root privileges. However, the mount points must be owned by the
# currently logged in user in order to be able to access them.
forUser=$(who | awk '{print $1}' | uniq)

exec /home/andreid/.local/scripts/usb/automount -u "$forUser"
