#!/usr/bin/bash -e

scriptName=$(basename "$0")

. "$FCLI_FUNCTIONS/stdin-or"

##
## Read "type" from a CLI arg, piped in, or from Rofi
##

type=$(stdin_or "$1")

if [ -z "$type" ]; then
  type=$(
    printf "draft,permanent,literature,snippet" \
      | rofi -dmenu \
        -p "$scriptName:" \
        -sep "," \
        -i \
        -case-sensitive false
  )
fi

##
## Template content
##

echo "---"
echo "id: \"$(random uuid)\""

case "$type" in
  draft)
    echo "type: \"note-draft\""
    ;;
  permanent)
    echo "type: \"note-permanent\""
    echo "topic: \"\""
    echo "tags: []"
    ;;
  literature)
    echo "type: \"note-literature\""
    echo "source: \"\""
    ;;
  snippet)
    echo "type: \"snippet\""
    echo "syntax: \"sh\""
    echo "description: \"\""
    echo "url: \"\""
    echo "tags: []"
    ;;
  *)
    fancy-log error \
      -v type "$type" \
      -v available_commands "draft,permanent,literature,snippet" \
      "Unknown type"
    exit 1
    ;;
esac

echo "date: \"$(date-long)\""
echo "time: \"$(date +"%H:%M:%S")\""
echo "---"
