#!/usr/bin/bash -e

scriptName=$(basename "$0")

# Update hosts file with blocking lists for fakenews, gambling, social media
# and tracking
updateHosts() {
  sudo curl https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -o /etc/hosts.steven

  sudo cp /etc/hosts /etc/hosts.bak
  sudo cp /etc/hosts.own /etc/hosts.own.bak

  sudo cat /etc/hosts.own | sudo tee /etc/hosts > /dev/null
  sudo cat /etc/hosts.steven | sudo tee -a /etc/hosts > /dev/null

  doomst --type success "$scriptName - /etc/hosts" \
    "Fakenews, gambling, social media and tracking hosts file updated"
}

# Update pacman packages
updatePacman() {
  # Clean pacman cache
  sudo rm -R /var/lib/pacman/sync

  # Update package database from scratch
  sudo pacman -Syyuv --noconfirm --needed

  # update i3blocks widgets with signal 10
  pkill -SIGRTMIN+10 i3blocks

  doomst --type success --title "$scriptName - pacman" --message "Packages updated"
}

updatePacmanDB() {
  # Refreh security keys, usefull when they expire or become invalid causing
  # package upgrades to fail due to signature issues
  sudo pacman-key --refresh-keys

  # Update package database
  sudo pacman -Syy --noconfirm

  # Update keyring
  sudo pacman -Sy archlinux-keyring

  # Clear package cache in case of corrupted packages or to free up disk space
  sudo pacman -Sc

  packageCount=$(pacman -Qu | wc | awk '{print $1}')
  fancy-log success -v pkg_count "$packageCount" "Package database and security keys updated"

  if command -v i3blocks >/dev/null 2>&1; then
    # update i3blocks widgets with signal 10
    pkill -SIGRTMIN+10 i3blocks
  fi
}

case "${1:-all}" in
  hosts) updateHosts ;;
  packages) updatePacman ;;
  packages-db) updatePacmanDB ;;
  all)
    # updateHosts
    updatePacman
    ;;
  *)
    fancy-log error -v arg "$1" "Invalid argument" 
esac
