#!/bin/sh -eu

# absolute dir path of this script file
dirpath=$(dirname "$(realpath "$0")")

echo "###############################################"
echo "# 1. Install base packages"
echo "###############################################"

sudo pacman --noconfirm -S git openssh

dotfile_home="$HOME/Work/andreidmt/dotfiles"
git clone git@github.com:andreidmt/dotfiles.git "$dotfile_home"

echo "###############################################"
echo "# 2. Create core directories"
echo "###############################################"

mkdir -p "$HOME/Downloads"
mkdir -p "$HOME/Media"
mkdir -p "$HOME/Backups"
mkdir -p "$HOME/Pictures/Wallpapers"
mkdir -p "$HOME/Pictures/Screenshots"
mkdir -p "$HOME/Work/asd14"

