#!/usr/bin/env dash

# shellcheck source=../../@0_fancy-posix-utils/functions/stdin-or
. "$FCLI_FUNCTIONS/stdin-or"

# shellcheck source=../../@0_fancy-posix-utils/functions/predicates
. "$FCLI_FUNCTIONS/predicates"

export LOG_NAMESPACE="doomst"
export LOG_LEVEL="info"

# NAME
#   doomst - Doomguy themed dunst notification script
# 
# SYNOPSIS
#   doomst -t <title> -m <message> -p <type>
# 
# DESCRIPTION
#   Doomguy themed dunst notification
# 
# OPTIONS
#   -t, --title TITLE      Title of the notification
#   -m, --message MESSAGE  Message of the notification
#   -p, --type TYPE        Type of the notification (default: info)
#                          Values: info, error, success
#
# SEE ALSO
#  dunst(1)

while [ "$#" -gt 0 ]; do
  case $1 in
    -p|--type)
      if [ "$2" ]; then
        type="$2"; shift
      else
        fancy-log error -v option "$2" "Option require a value"
        exit 1
      fi
    ;;
    *) break ;;
  esac
  shift
done

title=$(stdin_or "$title")

case ${type:-info} in
  success) 
    icon="$HOME/doomguy.png"
    urgency="normal"
  ;;
  error) 
    icon="$HOME/doomguy-blood.png" 
    urgency="critical"
  ;;
  *) 
    icon="$HOME/doomguy.png" 
    urgency="normal"
  ;;
esac

notify-send "$@" --icon "$icon" --urgency $urgency
