#!/usr/bin/env sh

# -e: exit on error, -u: error on undefined variable
set -eu 

# NAME
#  git-download - Download or update a git repository
#
# SYNOPSIS
#  git-download <git_address> <install_path>
#
# DESCRIPTION
#  Downloads a git repository to the given path. If the path already exists,
#  updates the repository via "git pull".
#
# SEE ALSO
#  git(1)

if [ "$#" -ne 2 ]; then
  fancy-log error "Usage: git-download <git_address> <install_path>" >&2
  exit 1
fi

export LOG_NAMESPACE=" git-download"
export LOG_LEVEL="info"

git_address=$1
path=$2

if [ -d "$path" ]; then
  fancy-log info -v address "$git_address" "Updating ..."

  cd "$path" && git pull
else
  fancy-log info -v address "$git_address" "Cloning ..."

  mkdir -p "$path"
  git clone --depth 1 "https://github.com/$git_address" "$path"
fi

