#!/usr/bin/env sh

export LOG_NAMESPACE="has-file-changed"
export LOG_LEVEL="info"

file_path="$1"
if [ -z "$file_path" ]; then
  fancy-log error "No file path provided"
  exit 1
fi

##
## Main
##

past_value_file="$CORE_TMP/hdp_$name"
past_value=$(cat "$past_value_file" 2> /dev/null || echo 0)
now_in_seconds=$(date +%s)
seconds_in_a_day=86400

if [ $((now_in_seconds - past_value)) -lt $((count * seconds_in_a_day)) ]; then 
  exit 1
fi

echo "$now_in_seconds" > "$past_value_file"
