#!/usr/bin/env sh

# Post script for "aws" HMVC module. 
#
# DESCRIPTION
#  Everything my the module should be setup and ready for use by now. Use this
#  to tidy up and perform any final tasks before the module can be used.

echo "󰸏 Updating AWS CLI..."

zip_file="$AWSM_TMP/awscliv2.zip"
mkdir -p "$AWSM_TMP" "$AWSM_LOCAL/aws-cli" "$AWSM_BIN"

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "$zip_file" 
unzip -oq "$zip_file" -d "$AWSM_TMP"

"$AWSM_TMP/aws/install" --update \
  --bin-dir "$AWSM_BIN" \
  --install-dir "$AWSM_LOCAL/aws-cli"

rm -rf "$AWSM_TMP"
