#!/usr/bin/env sh

# Redirect stderr to stdout for complete logging
exec 2>&1

{
  # Check battery status every 5 seconds
  while true; do
    ./alert-battery
    sleep 5
  done &
} | sed 's/^/[battery-alert] /'
