#!/usr/bin/env dash

. "$CORE_FUNCTIONS/die"

# NAME
#  nvim-config - Get and set NVim config
#
# SYNOPSIS
#  nvim-config <command>
#
# COMMANDS
#  get    - Get the current NVim config
#  change - Change the current NVim config
#
# DESCRIPTION
#  Switch between NVim configs. The configs are stored in $NVIM_CONFIG.
#
# SEE ALSO
#  choose(1)

get_config_name() {
  if [ ! -L "$HOME/.config/nvim" ]; then
    echo "custom dir"
  fi

  readlink "$HOME/.config/nvim" \
    | sed "s|$NVIM_CONFIG||" \
    | sed "s|/||"
}

change_config() {
  config_name=$(find "$NVIM_CONFIG" -maxdepth 1 -type d \
    | sed "s|$NVIM_CONFIG||" \
    | sed '/^$/d' \
    | sed 's|^/||' \
    | choose -p "$NVIM_ICON Change NVim config:"
  )

  if [ -z "$config_name" ]; then
    exit 1
  fi

  if [ ! -d "$NVIM_CONFIG/$config_name" ]; then
    die "Config <u>$config_name</u> not found"
  fi

  if [ -L "$HOME/.config/nvim" ]; then
    rm "$HOME/.config/nvim"
    ln -s "$NVIM_CONFIG/$config_name" "$HOME/.config/nvim"
    echo " Switched NVim config to $(underline "$config_name")"
  fi
}

##
## Main
##

if [ ! -L "$HOME/.config/nvim" ]; then
  die "Cannot switch config, ~/.config/nvim is not a symlink"
fi

case "${1:-get}" in
  get) 
    get_config_name 
  ;;

  change)
    change_config

    # update i3blocks widgets with signal 10
    pkill -SIGRTMIN+10 i3blocks
  ;;

  *) die "Command \"$1\" not recognized" ;;
esac
