#!/usr/bin/env sh

switch_node() {
  nvmrc_file="${PWD}/.nvmrc"
  current_version=$(nvm current)

  if [ -f "$nvmrc_file" ]; then
    nvmrc_version=$(cat "$nvmrc_file")
    nvmrc_version_installed=$(nvm ls "$nvmrc_version" | grep -c "N/A")

    echo " Found .nvmrc file with $(stylize underline "$nvmrc_version") version"

    if [ "$current_version" = "$nvmrc_version" ]; then
      echo " Already using $(stylize underline "$nvmrc_version") version"
    elif [ "$nvmrc_version_installed" -eq 0 ]; then
      echo " $nvmrc_version already installed, $(stylize underline "switching")..."
      nvm use "$nvmrc_version"
    else
      echo " $nvmrc_version is not installed, $(stylize underline "installing")..."
      nvm install "$nvmrc_version"
    fi
  else
    if [ "$current_version" != "$NVMM_DEFAULT_VERSION" ]; then
      echo " No .nvmrc file found, switching to $(stylize underline "default") version"
      nvm use "$NVMM_DEFAULT_VERSION"
    fi
  fi
}

