#!/bin/sh

NAME="~/.scripts/tools/mic"
CMD=${1:-toggle}

function setStatus {
    volume=$(amixer sget Capture | grep -E 'Front Left: Capture' | awk '{print $(NF-1)}' | grep -Eo '[0-9]{1,}')
    isMute=$(amixer sget Capture | grep -E 'Front Left: Capture' | awk '{print $NF}' | grep -Eo '\w{2,3}')

    case $isMute in
     "off") status="Mic muted $volume%" ;;
     "on") status="Mic $volume%" ;;
    esac
}

case "$CMD" in
    "toggle")
        amixer -q -D pulse sset Capture toggle
    ;;
    "mute")
        amixer -q -D pulse sset Capture mute
    ;;
    "up")
        amixer -q -D pulse sset Capture 10%+
        info="(+10%)"
    ;;
    "down")
        amixer -q -D pulse sset Capture 10%-
        info="(-10%)"
    ;;
    "status")
        setStatus
        echo $status
    ;;
esac

case "$CMD" in
    "toggle"|"mute"|"up"|"down")
        setStatus
        notify "$NAME" "$status $info"
    ;;
esac
