#!/usr/bin/lua

--
-- Author      : Andrei Dumitrescu <andrei@codemachiner.com>
-- Dep packages: [ date, scrot, notify-send ]
-- License     : MIT
-- Link        : github.com/andreid/dotfiles/.scripts/cm__screenshot
--

package.path = package.path .. ";" .. os.getenv("HOME") .. "/.scripts/?.lua"
require( "common" ) -- import `os.run`

WHAT = ""
if (arg[1] == "-t") then
    WHAT = arg[2] == "focus" and "-u" or ""
end

NOW = os.run( 'date +"%Y-%B-%d-%A-%R:%S"' )
FILENAME = "Screenshot_"..NOW..".png"
NOTIFY_MSG = "Captured screen saved in\n<u>~/Screenshots/"..FILENAME.."</u>"

os.execute( "scrot '"..FILENAME.."' "..WHAT.." -e 'mv $f ~/Screenshots/'" )
os.execute( "notify-send -i ~/doomguy.png  -t 5000 '~/.scripts/cm__screenshot' '"..NOTIFY_MSG.."'" )

print(arg[1])
