#!/bin/sh

NAME="~/.scripts/tools/vol"
CMD=${1:-toggle}

function setStatus {
    volume=$(amixer sget Master | grep -E 'Front Left: Playback' | awk '{print $(NF-1)}' | grep -Eo '[0-9]{1,}')
    isMute=$(amixer sget Master | grep -E 'Front Left: Playback' | awk '{print $NF}' | grep -Eo '\w{2,3}')

    case $isMute in
     "off") status="Vol muted $volume%" ;;
     "on") status="Vol $volume%" ;;
    esac
}

case "$CMD" in
    "toggle")
        amixer -q -D pulse sset Master toggle
    ;;
    "mute")
        amixer -q -D pulse sset Master mute
    ;;
    "up")
        amixer -q -D pulse sset Master 10%+
        info="(+10%)"

    ;;
    "down")
        amixer -q -D pulse sset Master 10%-
        info="(-10%)"
    ;;
    "status")
        setStatus
        echo $status
    ;;
esac

case "$CMD" in
    "toggle"|"mute"|"up"|"down")
        setStatus
        notify "$NAME" "$status $info"
    ;;
esac
