#!/usr/bin/env dash

. "$CORE_FUNCTIONS/is-process-running"

# DESCRIPTION
#  Start `polybar` if it is not already running, otherwise restart it.
# 
# ERROR CODES
#  1 Xorg is not running
#
# SEE ALSO
#  polybar(1)

if ! is_process_running "Xorg"; then
  echo "Xorg is not running, not starting polybar" >&2
  exit 1
fi

if is_process_running "polybar"; then
  killall -q polybar
fi

polybar top-a &
polybar top-b &
polybar bottom &

