#!/usr/bin/env bash

set -e

print_help() {
  local script_name=$(basename "$0")

  cat << EOF
NAME
 $script_name - AWS profile utilities

SYNOPSIS
 $script_name <command> [options] <profile_name>

COMMANDS
- ls|list       List all profiles in the AWS credentials file

- details       Output all properties from the AWS config file (including 
                related sso-session if one exists)
  OPTIONS
  --also-credentials  Include properties from the AWS credentials file

- get-property  Output the value of a specified field for the given profile

  OPTIONS
  <field_name>  The field name to fetch the value for

- exists        Check if the given profile exists

EXAMPLES
  $script_name ls
  $script_name details my-profile
  $script_name get-property my-profile region
EOF
}

parse_arguments() {
  COMMAND="$1"
  shift 

  while :; do
    case $1 in
      -h|--help)
        print_help
        exit 0
      ;;
      
      -c|--also-credentials)
        ALSO_CREDENTIALS="true"
      ;;

      # Standalone "--" terminates argument processing
      --) shift; break ;;

      # Argument not recognized
      -?*)
        echo "Error: Unknown argument $1" >&2
        exit 1
      ;;

      # anything else, considered as non-option argument
      *) break ;;
    esac
    shift
  done
}

getSection() {
  local header_title="$1"
  local contents="$(cat -)"

  echo "$contents" \
    | grep --after-context=100 "^\[.*$header_title.*\]" \
    | awk "NR==1 {next} /^\[/ {exit} {print}" \
    | awk '{if ($1=="") exit; print}'
}

get_profile_field() {
  local field_name="$1"
  local properties="$2"

  echo "$properties" \
    | grep "^$field_name" \
    | awk -F'=' '{print $2}' \
    | sed 's/^[[:blank:]]*//'
}

getAllProfileProperties() {
  local profile_name="$1"
  local contents=$(cat -)
  local properties=$(echo "$contents" | getSection "$profile_name")

  echo "$properties"

  if [[ "$properties" =~ sso_session ]]; then
    local sso_name=$(get_profile_field "sso_session" "$properties")
    
    echo "$contents" | getSection "$sso_name"
  fi
}

get_profile_details() {
  local profile_name="$1"
  local aws_files=(~/.aws/config)

  if [ "$ALSO_CREDENTIALS" = "true" ]; then
    aws_files+=(~/.aws/credentials)
  fi

  for file in "${aws_files[@]}"; do
    if [ ! -f "$file" ]; then
      continue
    fi
    getAllProfileProperties "$profile_name" < "$file"
  done
}

get_profile_property() {
  local profile_name="$1"
  local field_name="$2"
  local properties=$(get_profile_details "$profile_name")
  local field_value=$(get_profile_field "$field_name" "$properties")

  if [ -n "$field_value" ]; then
    echo "$field_value"
    exit 0
  fi

  exit 1
}

##
## Main
##

parse_arguments "$@"

case "$COMMAND" in
  ls|list) 
    grep -E '^\[(profile )?([a-zA-Z0-9_-]+)\]$' ~/.aws/config \
      | sed -E 's/^\[(profile )?([a-zA-Z0-9_-]+)\]$/\2/'
  ;;

  details) 
    get_profile_details "${@:2}" 
  ;; 

  get-property) 
    get_profile_property "${@:2}" 
  ;; 

  exists) 
    if grep -E "^\[profile $2\]$" ~/.aws/config > /dev/null; then
      exit 0
    fi

    echo "Profile \"$2\" does not exist" >&2
    exit 1
  ;;

  *) 
    print_help >&2
    exit 1
  ;;
esac
