#!/usr/bin/sh

case "$BLOCK_BUTTON" in
  # Left click
  1) $TERMINAL -e sys_upgrade ;;

  # Middle click
  2) ;;

  # Right click
	3) ;;

  # Scroll up, increase volume
  4) ;;

  # Scroll down, decrease volume
  5) ;;
esac

PACKAGE_COUNT=$(pacman -Qu | wc | awk '{print $1}')

echo "$PACKAGE_COUNT packages"

# i3blocks red background
if [ $PACKAGE_COUNT -gt 0 ]; then
  exit 33
fi
