#!/usr/bin/sh

# Test out with email client open, increase until you cant read titles
blur="10x5"
wallpaper=/tmp/i3lock-wall.png

# take screenhot
shotgun $wallpaper

# apply blur
magick $wallpaper -blur $blur $wallpaper

# lock screen
i3lock -i $wallpaper

# cleanup
rm $wallpaper

