#!/bin/sh

# Location of package in AUR repository
packageName=$1
packageFileName=$packageName.tar.gz
packageURL=https://aur.archlinux.org/cgit/aur.git/snapshot/$packageFileName

# Download and extract package
curl -sO "$packageURL"
tar -xvf "$packageFileName"

# Build
cd "$packageName" && makepkg --noconfirm -si && cd ..

# Cleanup
rm "$packageFileName"
rm -rf "$packageName"
