#!/usr/bin/sh

. "$LIBRARY_HOME/die.sh"

case ${1:-read} in
  create) 
    url="$2"
    title="$3"
    description="$4"
    now=$(date_iso)

    echo -e "\"${url}\",\"${title}\",\"${description}\",\"${now}\"" >> ~/bookmarks.csv
  ;;

  read)
    while IFS=, read url title description 
    do
      echo "URL: $url"
      echo "Title: $title"
      echo "Description: $description"
      echo
    done < ~/bookmarks.csv
  ;;

  *)
    die "Command \"$1\" not recognized"
  ;;
esac
