#!/usr/bin/sh -e

. "$LIBRARY_HOME/read-stdin-or.sh"
. "$LIBRARY_HOME/check-exists.sh"

if checkExistsInPath "$1" -eq 0; then
  echo "found $1"
else
  echo "not found $1"
fi

# copy(input)
# Put piped data or passed args into clipboard.

input=$(readStdinOr "$@")

# wayland 
if checkExistsInPath "wl-copy" -eq 0; then
  wl-copy "$input"
fi

# X
if checkExistsInPath "xsel" -eq 0; then
  printf "%s" "$input" | xsel --primary --input 
  printf "%s" "$input" | xsel --clipboard --input 
fi

