#!/bin/bash -e

. "$LIBRARY_HOME/die.sh"

# List all available droplets ("doctl auth init" before)
list() {
  query="map({\
    id,\
    name,\
    ip_public: .networks.v4 | map(select(.type == \"public\"))[0] | .ip_address,\
    status,\
    price:.size.price_monthly\
  })"

  doctl compute droplet list -o json | jq "$query" 
}

# SSH into a droplet
connect() {
  name=$1
  user="${2:-"root"}"

  jqSelector="map(select(.name==\"$name\"))[0].ip_public"
  ip=$(list | jq -r "$jqSelector")
  tunnel="$3"

  if [ -z "$tunnel" ]; then
    doomst --message "# connecting to \"$name\" droplet \n\n\$ ssh $user@$ip"
    ssh "$user@$ip"
  else
    doomst --message "# connecting to \"$name\" droplet \n\n\$ ssh -L $tunnel $user@$ip"
    ssh -L "$tunnel" "$user@$ip"
  fi
}

case "${1:-ls}" in
  ls|list) list "${@:2}" ;;
  connect) connect "${@:2}" ;;
  *) die "Command \"$1\" not recognized" ;;
esac
