#!/usr/bin/sh

SCRIPT_NAME="~/.local/bin/notes"
CMD=${1:-ls}

NOTES_HOME="$HOME/Notes"
NOTES_SRC="$NOTES_HOME/src"
NOTES_DIST="$NOTES_HOME/dist"

TODAY_PATH="$NOTES_SRC/$(date +%Y)/$(date +%m.%B)/$(date +%d.%A)"

mkdir -p "$TODAY_PATH"
mkdir -p "$NOTES_DIST"

case $CMD in
  #
  # Create a new markdown file, or open existing, for today's notes
  #
  create)
    NOTE_PATH="$TODAY_PATH/$(date +%H:%M).md"

    if [ ! -f $NOTE_PATH ]; then
      echo -e "date: $(date +%Y-%m-%d)\ntime: $(date +%H:%M)\ntype: \ntopic: \ncontext: \n\n---\n\n" > $NOTE_PATH
    fi

    # Relevant context for vim's NerdTree
    cd "$NOTES_SRC"

    nvim -c "norm G" \
      -c "norm zz" \
      -c "set spell" \
      $NOTE_PATH
  ;;

  #
  #
  #
  find)
    NOTE=$(notes ls \
    | rofi -dmenu \
      -eh 4 \
      -sep '|' \
      -p "notes" \
      -i \
      -markup-rows \
      -lines 4 \
      -case-sensitive false)

    if [ ! -z "$NOTE" ]
    then
      echo "$NOTE" \
        | sanitize html \
        | tail -n 1 \
        | xargs st -e notes open
    fi
  ;;

  #
  # List all notes
  #
  ls)
    ALL_NOTES=$(rg --files $NOTES_SRC | rg .md | sort -r)
    META_COUNT=2
    
    for NOTE_PATH in $ALL_NOTES
    do
      TITLE=$(rg "^# " --max-count 1 $NOTE_PATH | sed -e "s/# //g")
      META=$(head -n $META_COUNT $NOTE_PATH)

      echo -e "${TITLE:-"--"}\n<small>$META\n$NOTE_PATH</small>|"
    done
  ;;

  open)
    [ -z "$2" ] && read NOTE_PATH || NOTE_PATH="$2"

    # Relevant context for vim's NerdTree
    cd "$NOTES_SRC"

    nvim -c "norm zz" \
      -c "set spell" \
      "$NOTE_PATH"
  ;;

  #
  # Make a PDF out from a markdown note file
  #
  build)
    NOTE_PATH=$2
    PDF_NAME="$(basename "$NOTE_PATH" .md).pdf"

    TITLE="$(cat $NOTE_PATH | grep '# Notes for' | sed 's/# //')"
    CONTENT=""

    pandoc \
      --from gfm \
      --pdf-engine=xelatex \
      --toc \
      --metadata=title:"$TITLE" \
      -V geometry:a4paper \
      -V geometry:margin=3.5cm \
      -V linkcolor:blue \
      -o "$NOTES_DIST/$PDF_NAME" "$NOTE_PATH" &
  ;;

  #
  # Open zathura with the PDF of the most recent notes file
  #
  read-last)
    PDF_PATH="$NOTES_DIST/$(ls -r "$NOTES_DIST" | head -n 1)"

    zathura $PDF_PATH
  ;;

  *)
    notify-bad "$SCRIPT_NAME" "Command \"$CMD\" not recognized"

    exit 1
  ;;
esac
