#!/usr/bin/sh -e

scriptName='~/.local/scripts/notes'
notesHome="$HOME/Work/andreidmt.dotfiles-private/Notes"
draftsPath="$notesHome/draft"

create() {
  mkdir -p "$draftsPath"
  newNotePath="$draftsPath/$(date +%y-%j).md"

  if [ ! -f "$newNotePath" ]; then
    printf "# %s\n" "$(date '+%A, %d %B %Y')" > "$newNotePath"
  fi

  printf "\n## %s\n" "$(date '+%H:%M')" >> "$newNotePath"

  # Relevant context for vim's NerdTree
  cd "$notesHome"

  nvim -c "norm G" -c "norm zz" -c "set spell" "$newNotePath"
}

open() {
  [ -z "$1" ] && read -r notePath || notePath="$1"

  if [ -f $notePath ]; then
    # Relevant context for vim's NerdTree
    cd "$notesHome"

    nvim -c "norm zz" -c "set spell" "$notePath"
  else
    notify-bad $scriptName "Cannot find note at \"$notePath\""
    exit 1
  fi
}

list() {
  notes=$(rg --files "$notesHome" \
    | rg .md \
    | sort -r \
  )

  for path in $notes
  do
    title=$(rg "^# " --max-count 1 "$path" | sed -e "s/# //g")
    type=$(cat "$path" \
      | sed -n '/^```toml/,/^```/ p' \
      | grep TYPE \
      | awk -F'[ ="]+' '{ print tolower($2) }'
    )

    if [ -z "$type" ]; then
      printf "%s\n<small>%s</small>|" "${title:-'--'}" "$path"
    else
      printf "[%s] %s\n<small>%s</small>|" "$type" "${title:-'--'}" "$path"
    fi
  done
}

ask() {
  note=$(notes list \
    | rofi -dmenu \
      -eh 2 \
      -sep '|' \
      -p " :" \
      -i \
      -markup-rows \
      -case-sensitive false \
  )

  if [ -n "$note" ]; then
    echo "$note" \
      | sanitize html \
      | tail -n 1 \
      | xargs $TERMINAL -t such-important -e notes open
  fi
}

case "${1-ask}" in
  ask) ask ;;
  create) create ;;
	list) list ;;
	open) open $2;;
  *)
    notify-bad "$scriptName" "Command \"$1\" not defined"
    exit 1
  ;;
esac
