#!/usr/bin/sh

input=${1:-$(</dev/stdin)}

# Need at least one parameter
if [ -z "$input" ]; then 
  echo "No message provided"
  exit 1
fi

# Props
title=$input
message=$2
icon=$3

# default icon if none set
if [ -z "$3" ]; then 
  icon=~/doomguy.png
fi

dunstStatus=$(ps -C dunst >/dev/null && echo "running" || echo "not-running")

if [ "$dunstStatus" = "running" ]; then
  dunstify -i "$icon" -t 5000 "$title" "$message"
else
  echo ""
  echo "# $title"
  echo "# $message"
  echo ""
fi
