#!/usr/bin/bash

# Run a command across all projects in an Nx monorepo without the need of a
# "target" defined in each "project.json" file.
#
# Similar to Lerna's "lerna exec" command.
# https://github.com/lerna/lerna/tree/main/libs/commands/exec#readme
#
# Usage: nx-exec "command"
# Example: nx-exec "npx tsc --noEmit"

command=$1
projects=$(find . -name 'project.json' -not -path './node_modules/*')
passCount=0
failCount=0

cowsay "Running \"$command\" in $(echo "$projects" | wc -l) projects..."

for project in $projects; do
  name=$(jq -r '.name' "$project")

  # not all project.json files have a "name" field
  if [ "$name" == "null" ]; then
    name=$project
  fi

  output=$(cd "$(dirname "$project")" && eval "$command" > /dev/null 2>&1)

  # check previous command exit code
  if [ "$?" -eq 0 ]; then
    # echo -e "\033[0;32m✔\033[0m $name"
    passCount=$((passCount + 1))
  else
    echo -e "\033[0;31m✖\033[0m $name"
    failCount=$((failCount + 1))
  fi
done

echo ""
echo -e "\033[0;32mPASS:\033[0m $passCount"
echo -e "\033[0;31mFAIL:\033[0m $failCount"
