#!/usr/bin/sh

. "$LIBRARY_HOME/die.sh"

workPath="$HOME/Work"

# Piped value or first param
[ -z "$1" ] && read -p "name: " -r projectName || projectName="$1"

if [ -d "$workPath/$projectName" ]; then
  # Relevant context for vim's NerdTree
  cd "$workPath/$projectName"

  nvim README.md
else
  die "Cannot find project folder \"$workPath/$projectName\""
fi
