#!/usr/bin/env bash

. "$LIBRARY_HOME/die.sh"

WORK_PATH="$HOME/Work"

# Piped value or first param
[ -z "$1" ] && read -p "name: " -r projectName || projectName="$1"

if [ ! -d "$WORK_PATH/$projectName" ]; then
  die "Cannot find project folder \"$WORK_PATH/$projectName\""
fi

cd "$WORK_PATH/$projectName" && nvim README.md
