#!/usr/bin/sh -eu

. "$LIBRARY_HOME/die.sh"

length=${2:-6}

case ${1:-readable} in
  readable)
    first=$(tr -dc 'a-z' < /dev/urandom | fold -w "$(("$length"/2))" | head -n 1)
    second=$(tr -dc '0-9' < /dev/urandom | fold -w 3 | head -n 1)

    echo "$first-$second"
  ;;

  whatever)
    tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w "$length" | head -n 1
  ;;

  uuid)
    cat /proc/sys/kernel/random/uuid
  ;;

  *)
    die "Command \"$1\" not recognized"
  ;;
esac
