#!/usr/bin/sh

SCRIPT_NAME="~/.local/bin/random"
CMD=${1:-readable}

case $CMD in
  readable)
    FIRST=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 3 | head -n 1)
    SECOND=$(cat /dev/urandom | tr -dc '0-9' | fold -w 3 | head -n 1)

    echo "$FIRST-$SECOND"
  ;;

  whatever)
    LENGTH=${2:-6}

    cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $LENGTH | head -n 1
  ;;

  uuid)
    cat /proc/sys/kernel/random/uuid
  ;;

  *)
    notify-bad "$SCRIPT_NAME" "Command \"$CMD\" not recognized"

    exit 1
  ;;
esac
