#!/usr/bin/bash -e

# Join an array with a custom delimiter.
join() {
  local delimiter="$1"
  shift
  local array=("$@")

  local old_ifs=$IFS
  IFS="$delimiter"
  local joined_array="${array[*]}"

  IFS=$old_ifs
  echo "$joined_array"
}

opt_snippets=" Snippets"
opt_bookmarks=" Bookmarks"
opt_color_picker=" Pick color"
opt_projects=" Projects"
opt_power=" Power"

# optionNotes=" Notes"
# optionRecord="辶 Record"
# optionDictionary="﬜ Dictionary"
# optionDisplays=" Displays"

menu_items=(
  "$opt_snippets"
  "$opt_bookmarks"
  "$opt_color_picker"
  "$opt_projects"
  "$opt_power"
)

shortcuts=(
  " + s"
  " + b"
)

input_format=()

for index in "${!menu_items[@]}"; do
  item="${menu_items[$index]}"
  shortcut="${shortcuts[$index]}"

  if [ -z "$shortcut" ]; then
    input_format+=("${item}")
    continue
  fi

  input_format+=("${item} <small>[${shortcut}]</small>")
done

choice="$(join $'\n' "${input_format[@]}" \
  | rofi -markup-rows -dmenu -p " "
)"

# selected=$( | rofi -dmenu -markup-rows -i -p "Select an option:" -theme ./custom_theme.rasi)


# choice="$(echo -e "$optionNotes\n$opt_snippets\n$optionRecord\n$opt_color_picker\n$opt_projects\n$optionDictionary\n$optionDisplays\n$opt_power" \
#   | rofi -dmenu --prompt " "
# )"

case $choice in
  # "$optionNotes") notes ;;
  "$opt_snippets"*) zofi snippets copy ;;
  "$opt_bookmarks"*) zofi bookmarks copy ;;
  # "$optionRecord") record ;;
  "$opt_color_picker"*) screenshot pick-color ;;
  "$opt_projects"*) projects.find ;;
  # "$optionDictionary") rofi.dictionary ;;
  # "$optionDisplays") rofi.displays ;;
  "$opt_power"*) rofi_power ;;
esac
