#!/usr/bin/sh

# Exit script if any statement returns a non-true return value
set -e

# Exit script if trying to use an uninitialised variable
set -u

optionNotes=" Notes"
optionRecord="辶 Record"
optionProjects=" Projects"
optionTemplates=" Templates"
optionDictionary="﬜ Dictionary"
optionDisplays=" Displays"
optionPower=" Power"

chosen="$(echo -e "$optionNotes\n$optionRecord\n$optionProjects\n$optionTemplates\n$optionDictionary\n$optionDisplays\n$optionPower" \
  | rofi -dmenu \
    -i \
    -p "" \
		-no-fixed-num-lines \
)"

case $chosen in
  "$optionNotes") notes ;;
  "$optionRecord") record ;;
  "$optionProjects") projects.find ;;
  "$optionTemplates") templates.find ;;
  "$optionDictionary") rofi.dictionary ;;
  "$optionDisplays") rofi.displays ;;
  "$optionPower") rofi.power ;;
esac
