#!/usr/bin/bash -eu

optionNotes=" Notes"
optionSnippets=" Snippets"
optionRecord="辶 Record"
optionColor=" Pick color"
optionProjects=" Projects"
optionDictionary="﬜ Dictionary"
optionDisplays=" Displays"
optionPower=" Power"

chosen="$(echo -e "$optionNotes\n$optionSnippets\n$optionRecord\n$optionColor\n$optionProjects\n$optionDictionary\n$optionDisplays\n$optionPower" \
  | rofi -dmenu \
    -p ""
)"

case $chosen in
  "$optionNotes") notes ;;
  "$optionSnippets") snippets ;;
  "$optionRecord") record ;;
  "$optionColor") screenshot pick-color ;;
  "$optionProjects") projects.find ;;
  "$optionDictionary") rofi.dictionary ;;
  "$optionDisplays") rofi.displays ;;
  "$optionPower") rofi.power ;;
esac
