#!/bin/sh -e

. "$LIBRARY_HOME/die.sh"

DIR="$HOME/Pictures/Screenshots"
NOW=$(date +"%Y-%B-%d-%A-%R:%S")

# Make sure Screenshots folder exists
mkdir -pv "$DIR"

case $1 in
  color-pick)
    colorpicker | copy
  ;;

  area)
    selection=$(hacksaw -f "-i %i -g %g")

    # dont quote, multiple params inside
    shotgun $selection - | xclip -t "image/png" -selection clipboard

    xclip -o -selection clipboard > "$DIR/area_$NOW.png"
  ;;

  window)
    selection=$(slop -f "-g %g")

    # dont quote, multiple params inside
    shotgun $selection - | xclip -t 'image/png' -selection clipboard

    xclip -o -selection clipboard > "$DIR/focus_$NOW.png"
  ;;

  all)
    if [ -n "$2" ]; then
      filename=$2
    else
      filename="screen_$NOW.png"
    fi

    shotgun "$DIR/$filename"

    doomst "$scriptName" "<u>Capturing entire screen</u>\n\n$DIR/$filename"
  ;;

  *)
    die "Command \"$1\" not recognized"
  ;;
esac
