#!/bin/sh

SCRIPT_NAME=\~/.local/scripts/screen
CMD=$1

case $CMD in
  auto-temp)
    screen-auto-temp
  ;;

  *)
    notify-bad "$SCRIPT_NAME" "Command \"$CMD\" not recognized"

    exit 1
  ;;
esac
