#!/bin/sh -e

scriptName=$(basename "$0")
screenshotHome="$HOME/Pictures/Screenshots"
now=$(date +"%Y-%B-%d-%A-%R:%S")

# Make sure Screenshots folder exists
mkdir -pv "$screenshotHome"

case $1 in
  pick-color)
    colorpicker --short --one-shot --preview | xclip -selection clipboard
  ;;

  area)
    selection=$(hacksaw -f "-i %i -g %g")
    dimension=$(echo "$selection" | awk '{print $4}' | awk -F+ '{print $1}')
    path="$screenshotHome/area_$now.png"

    # dont quote, multiple params inside
    shotgun $selection "$path"
    xclip -t 'image/png' -selection clipboard < "$path"
    doomst "$scriptName, area $dimension" "$path"
  ;;

  window)
    selection=$(slop -f "-g %g")
    dimension=$(echo "$selection" | awk '{print $2}' | awk -F+ '{print $1}') 
    path="$screenshotHome/window_$now.png"

    # dont quote, multiple params inside
    shotgun $selection "$path"
    xclip -t 'image/png' -selection clipboard < "$path"
    doomst "$scriptName, window $dimension" "$path"
  ;;

  all)
    filename=${2:-"screen_$now.png"}
    path="$screenshotHome/$filename"

    shotgun "$path"
    xclip -t 'image/png' -selection clipboard < "$path"
    doomst "$scriptName - screen" "$path"
  ;;

  *)
    doomst --type error "$scriptName" "$1"
    exit 1
  ;;
esac
