#!/bin/sh -eu

# Slugify a string, with ChatGPTs help
#
# @param {string} $1 - The input string to be slugified
# @return {string} - The slugified string

patternNonAlphanumeric='[^a-zA-Z0-9]'
patternDuplicateDashes='-+'
patternUppercase='[A-Z]'
patternLeadingTrailingDashes='^-+|-+$'

echo "$1" | sed -E \
  -e "s/$patternNonAlphanumeric/-/g" \
  -e "s/$patternDuplicateDashes/-/g" \
  -e "s/$patternUppercase/\L&/g" \
  -e "s/$patternLeadingTrailingDashes//g"

