#!/usr/bin/bash -e

. "$LIBRARY_HOME/die.sh"
. "$LIBRARY_HOME/read-stdin-or.sh"

# run(name, ...args)
# Runs a snippet file if it has +x permissions, otherwise output it's contents.
run() {
  read -r -a signature <<< "$(readStdinOr "$1")"

  path="$SNIPPETS_HOME/${signature[0]}"

  if [ ! -f "$path" ]; then
    die "Snippet '$path' does not exist"
  fi

  if [ -x "$path" ]; then
    $path "${signature[@]:1}"
  else
    head --bytes=-1 "$path" \
      | sed '/```toml/,/```/d'
  fi
}

# paste(name, ...args)
# Run a snippet and put it's content in the clipboard.
paste() {
  result=$(run "$1")

  if [ "$XDG_CURRENT_DESKTOP" = "sway" ]; then
    wl-copy "$result"
  fi

  if [ "$XDG_CURRENT_DESKTOP" = "x" ]; then
    printf "%s" "$result" | xsel -p -i 
    printf "%s" "$result" | xsel -b -i 

    # simulate paste actions, should work in almost all situations
    xdotool key shift+Insert
  fi
}

open() {
  name=$(readStdinOr "$1")

  # Relevant context for vim's NerdTree
  cd "$SNIPPETS_HOME"

  nvim -c "norm zz" -c "set spell" "$name"
}

ask() {
  rg --files --sortr modified "$SNIPPETS_HOME" \
    | sed 's/^.*\///' \
    | rofi -dmenu \
        -p "$1" \
        -i \
        -case-sensitive false
}

case ${1-ask-use} in
  ask-create)
    name=$(ask " create or edit snippet")
    [ -n "$name" ] && st -t such-important -e snippets open "$name"
  ;;
  ask-use)
    name=$(ask " use snippet")
    [ -n "$name" ] && paste "$name"
  ;;
  run) run "$2" ;;
  open) open "$2" ;;
  *) die "Command \"$1\" not defined" ;;
esac
