#!/bin/sh

SCRIPT_NAME="~/.local/bin/snippets"
CMD=${1:-ls}

SNIPPETS_HOME="${HOME}/.local/snippets"

case $CMD in
  #
  # Create a new snippet or open existing
  #
  create)
    NAME=$(snippets ls \
      | rofi -dmenu \
          -p "create or edit existing snippet" \
          -i \
          -case-sensitive false
    )

    if [ ! -z "$NAME" ]
    then
      # Relevant context for vim's NerdTree
      cd "$SNIPPETS_HOME"

      st -e nvim "$SNIPPETS_HOME/$NAME"
    fi
  ;;

  #
  # Interactive snippet search and paste into current focus
  #
  find)
    NAME=$(snippets ls \
      | rofi -dmenu \
          -p "snippets" \
          -i \
          -case-sensitive false
    )

    if [ ! -z "$NAME" ]
    then
      snippets paste $NAME
    fi
  ;;

  #
  # List all available snippet names
  #
  ls)
    cd $SNIPPETS_HOME && rg --files | sort -r
  ;;

  paste)
    NAME="$2"
    SNIP_PATH="${SNIPPETS_HOME}/${NAME}"

    if [ -f $SNIP_PATH ]; then
      DATA=$([ -x "${SNIP_PATH}" ] && bash "${SNIP_PATH}" || head --bytes=-1 ${SNIP_PATH})

      # put data in both main and middle mouse buffer 
      printf "$DATA" | xsel -p -i 
      printf "$DATA" | xsel -b -i 

      # simulate paste actions, should work in almost all situations
      xdotool key shift+Insert
    fi
  ;;

  *)
    notify-bad "$SCRIPT_NAME" "Command \"$CMD\" not recognized"

    exit 1
  ;;
esac
