#!/usr/bin/sh

SCRIPT_NAME=\~/.local/scripts/sys
CMD=$1

case $CMD in
  #
  #
  #
  dotfiles-sync)
    DOTFILES_REPO="$HOME/Work/dotfiles"

    rm -rf "$DOTFILES_REPO/.config"
    rm -rf "$DOTFILES_REPO/.local"

    mkdir -p "$DOTFILES_REPO/.local/share"
    mkdir -p "$DOTFILES_REPO/.config/nvim"
    mkdir -p "$DOTFILES_REPO/home"

    # Custom scripts
    cp -r "$HOME/.local/scripts" "$DOTFILES_REPO/.local"
    cp -r "$HOME/.local/statusbar" "$DOTFILES_REPO/.local"
    cp -r "$HOME/.local/snippets" "$DOTFILES_REPO/.local"

    # Share
    cp -r "$HOME/.local/share/applications" "$DOTFILES_REPO/.local/share"
    cp "$HOME/.config/mimeapps.list" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.local/share/fonts" "$DOTFILES_REPO/.local/share"

    # Vim
    cp "$HOME"/.config/nvim/*.vim "$DOTFILES_REPO/.config/nvim"
    cp "$HOME"/.config/nvim/*.lua "$DOTFILES_REPO/.config/nvim"
    cp -r "$HOME/.config/nvim/snippets" "$DOTFILES_REPO/.config/nvim"

    # Files
    cp "$HOME/.Xresources" "$DOTFILES_REPO/home"
    cp "$HOME/.xinitrc" "$DOTFILES_REPO/home"
    cp "$HOME/.gitconfig" "$DOTFILES_REPO/home"
    cp "$HOME/.profile" "$DOTFILES_REPO/home"

    # Other configs
    cp -r "$HOME/.config/zsh" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/i3" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/i3blocks" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/dunst" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/rofi" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/fontconfig" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/picom" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/sxiv" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/neofetch" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/gtk-3.0" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/redshift" "$DOTFILES_REPO/.config"
    cp -r "$HOME/.config/mimeapps.list" "$DOTFILES_REPO/.config"
  ;;

  #
  # Update package database
  #
  update)
    neofetch

    sudo pacman -Syy --noconfirm

    # Packages available for update
    PACKAGE_COUNT=$(pacman -Qu | wc | awk '{print $1}')
    
    notify "$SCRIPT_NAME" "Pacman database updated, ${PACKAGE_COUNT} available."

    # update i3blocks widgets with signal 10
    pkill -SIGRTMIN+10 i3blocks
  ;;

  #
  # Update ZSH plugins
  #
  update-zsh)
    ZSH_SYNTAX="git@github.com:zsh-users/zsh-syntax-highlighting.git"
    ZSH_SUGGESTIONS="git@github.com:zsh-users/zsh-autosuggestions.git"
    ZSH_POWER10K="git@github.com:romkatv/powerlevel10k.git"
    ZSH_NVM="git@github.com:lukechilds/zsh-nvm.git"

    rm -rf "$HOME/.local/bin/zsh-plugins"
    mkdir -p "$HOME/.local/bin/zsh-plugins"

    echo "###"
    echo "### ZSH Syntax Highlighting"
    echo "###"
    git clone "$ZSH_SYNTAX" "$HOME/.local/bin/zsh-plugins/zsh-syntax-highlighting"
    

    echo "###"
    echo "### ZSH Autosuggestions"
    echo "###"
    git clone "$ZSH_SUGGESTIONS" "$HOME/.local/bin/zsh-plugins/zsh-autosuggestions"

    echo "###"
    echo "### Powerlevel10k"
    echo "###"
    git clone "$ZSH_POWER10K" "$HOME/.local/bin/zsh-plugins/powerlevel10k"

    echo "###"
    echo "### nvm"
    echo "###"
    git clone "$ZSH_NVM" "$HOME/.local/bin/zsh-plugins/nvm"
  ;;


  #
  #
  #
  update-hosts)
    curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts > /etc/hosts.steven

    notify "$SCRIPT_NAME" "Fakenews, gambling, social media and tracking hosts file updated"
  ;;

  # 
  # Update package database and upgrade all
  #
  upgrade)
    neofetch

    sudo pacman -Syyuv --noconfirm
    
    notify "$SCRIPT_NAME" "Packages updated."

    # update i3blocks widgets with signal 10
    pkill -SIGRTMIN+10 i3blocks
  ;;

  #
  # Remove orphan packages and clear pacman cache
  #
  clean)
    ORPHAN_PACKAGES=$(pacman -Qtdq | tr '\n' ' ')

    if [ -n "$ORPHAN_PACKAGES" ]; then 
      echo "###"
      echo "### Orphan packages: $ORPHAN_PACKAGES"
      echo "###"

      sudo pacman -Rns "$ORPHAN_PACKAGES"

      notify "$SCRIPT_NAME clean" "Removed $(echo "$ORPHAN_PACKAGES" | wc) orphan packages"
    else
      notify "$SCRIPT_NAME clean" "No orphan packages found"
    fi

    sudo pacman -Sc

    notify "$SCRIPT_NAME clean" "After cache cleaup with \`pacman -Sc\`\n\n$(du -h /var/cache/pacman/pkg)"
  ;;

  #
  #
  #
  lock)
    LOCK_WALLPAPER=/tmp/i3lock-wall.png
    
    # Test this out with your email client open, 
    # increase until you cant read the title
    BLUR="10x5"

    # screenhot
    shotgun $LOCK_WALLPAPER

    # blur
    convert $LOCK_WALLPAPER -blur $BLUR $LOCK_WALLPAPER

    i3lock -i $LOCK_WALLPAPER
    rm $LOCK_WALLPAPER
  ;;

  #
  #
  #
  reload)
    xrdb ~/.Xresources
    # source ~/.config/zsh/.zshrc

    notify $SCRIPT_NAME "Reloading ~/.Xresources and ~/.zshrc"
  ;;

  *)
    notify-bad "$SCRIPT_NAME" "Command \"$CMD\" not recognized"

    exit 1
  ;;
esac
