#!/usr/bin/sh -eu

scriptName=$(basename "$0")
orphanPackages=$(pacman -Qtdq | tr "\n" " ")

if [ -n "$orphanPackages" ]; then 
  echo "Orphan packages found: $orphanPackages"
  sudo pacman -Rns $orphanPackages
  doomst --type success "$scriptName" "Removed $(echo "$orphanPackages" | wc -w) orphan packages"
else
  doomst "$scriptName" "No orphan packages found"
fi

sudo pacman -Sc
doomst "$scriptName" "After cache cleaup with \`pacman -Sc\`\n\n$(du -h /var/cache/pacman/pkg)"
