#!/usr/bin/sh -eu

SCRIPT_NAME=\~/.local/scripts/sys-update

# pacman-key --refresh-keys

# Update package database
sudo pacman -Syy --noconfirm

# Update keyring
sudo pacman -Sy archlinux-keyring

#
packageCount=$(pacman -Qu | wc | awk '{print $1}')

doomst "$SCRIPT_NAME" "Pacman database updated, ${packageCount} available."

# update i3blocks widgets with signal 10
pkill -SIGRTMIN+10 i3blocks
