#!/bin/sh

# Exit when any command fails
set -e

SCRIPT_NAME="~/.local/bin/unpack"
FILE=$1
FOLDER="unpacked-$FILE"        

mkdir -p "$FOLDER"

case "$FILE" in
  *.rar)
    unrar e "$FILE" "$FOLDER"
  ;;

  *.zip)
    unzip "$FILE" -d "$FOLDER"
  ;;

  *.tgz|*.tar.gz)
    tar -xzf "$FILE" -C "$FOLDER"
  ;;

  *.gz)
    gunzip "$FILE"
  ;;

  *.tar.xz)
    tar -xf "$FILE" -c "$FOLDER"
  ;;

  *)
    notify-bad "$SCRIPT_NAME" "Unknown archive format $FILE"

    exit 1
  ;;
esac
