#!/usr/bin/sh -e

. "$LIBRARY_HOME/die.sh"

archiveFile=$1
destFolder=${2-"unpacked-$archiveFile"} 

mkdir -p "$destFolder"

case "$archiveFile" in
  *.rar)
    unrar e "$archiveFile" "$destFolder"
  ;;

  *.zip)
    unzip "$archiveFile" -d "$destFolder"
  ;;

  *.tgz|*.tar.gz)
    tar -xzf "$archiveFile" -C "$destFolder"
  ;;

  *.gz)
    gunzip "$archiveFile"
  ;;

  *.tar.xz)
    tar -xf "$archiveFile" -c "$destFolder"
  ;;

  *)
    die "Unknown archive format $archiveFile"
  ;;
esac
