#!/usr/bin/sh

. "$LIBRARY_HOME/die.sh"

PROJECT_FOLDER=$1
PROJECT_PATH="$HOME/Work/$PROJECT_FOLDER" 

if [ ! -d "$PROJECT_PATH" ]; then
  die "Project folder \"$PROJECT_FOLDER\" does not exist"
fi

cd "$PROJECT_PATH"
nvim "$PROJECT_PATH/README.md"
