#!/usr/bin/env sh

# NAME
#  stilize - print text with different styles
#
# SYNOPSIS
#  stilize b|bold <text>
#  stilize u|underline <text>
#  stilize i|italic <text>

# /dev/tty redirect is used to ensure log does not inherit 
#
#
# parent's stdin
log_error() { log "$@" "stylize" < /dev/tty; }

case "$1" in
  b|bold) printf "\033[1m%s\033[0m" "$2"; ;;
  u|underline) printf "\033[4m%s\033[0m" "$2"; ;;
  i|italic) printf "\033[3m%s\033[0m" "$2"; ;;
  *) log_error "unknown command $1"; exit 1 ;; 
esac
