#!/usr/bin/env sh

# ╭─────────┤ color
# │ Print colored text to stdout
# │
# │ SYNOPSIS
# │   color <name> <text>
# │
# │ COLORS
# │   black, white, red, green, blue, yellow, cyan, gray
# ╰────

case "$1" in
  black) code=30 ;;
  white) code=37 ;;
  red) code=31 ;;
  green) code=32 ;;
  blue) code=34 ;;
  yellow) code=33 ;;
  cyan) code=36 ;;
  gray) code=90 ;;
  *)
    echo "Unknown color: $1" >&2
    exit 1
    ;;
esac

printf "\033[%sm%s\033[0m" "$code" "$2"
