#!/usr/bin/sh -eu

. "$LIBRARY_HOME/die.sh"

# nice()
# Output current date in a human-readable format.
# 
# Example:
# nice
# // => Monday, 4th July 2022, 15:22:57
nice() {
  dayOfTheMonth=$(date +%-e)

  case $dayOfTheMonth in
    1?) dayOfTheMonth="${dayOfTheMonth}th" ;;
    1)  dayOfTheMonth="${dayOfTheMonth}st" ;;
    2)  dayOfTheMonth="${dayOfTheMonth}nd" ;;
    3)  dayOfTheMonth="${dayOfTheMonth}rd" ;;
    *)  dayOfTheMonth="${dayOfTheMonth}th" ;;
  esac

  date "+%A, $dayOfTheMonth %B %Y, %T"
}

# iso()
# Output current date in ISO format.
#
# Example:
# iso
# // => 2022-07-05T13:12:45+02:00
iso() {
  date --iso-8601=seconds
}

# dayOfTheYear()
# Output current day of the year.
#
# Example:
# dayOfTheYear
# // => 186
dayOfTheYear() {
  date +%j
}

case ${1-nice} in
  nice) nice ;;
  dayOfTheYear) dayOfTheYear ;;
  iso) iso ;;
  *) die "Command '$1' does not exist" ;;
esac
