#!/usr/bin/bash -e

scriptName=$(basename "$0")

. "$LIBRARY_HOME/die.sh"
. "$LIBRARY_HOME/read-stdin-or.sh"

##
## Read "type" from a CLI arg, piped in, or from Rofi 
##

type=$(readStdinOr "$1")

if [ -z "$type" ]; then
  type=$(printf "draft,permanent,literature,snippet" | \
    rofi -dmenu \
      -p "$scriptName:" \
      -sep "," \
      -i \
      -case-sensitive false \
  )
fi

##
## Template content
##

echo "\`\`\`toml" 
echo "id=\"$(random uuid)\""

case "$type" in
  draft)
    echo "type=\"note-draft\""
  ;;
  permanent)
    echo "type=\"note-permanent\""
    echo "topic=\"\""
    echo "tags=[]"
  ;;
  literature)
    echo "type=\"note-literature\""
    echo "source=\"\""
  ;;
  snippet)
    echo "type=\"snippet\""
    echo "syntax=\"sh\""
    echo "description=\"\""
    echo "url=\"\""
    echo "tags=[]"
  ;;
  *)
    die "Nothing matched"
  ;;
esac

echo "createdAt=\"$(snippets run "date iso")\""
echo "\`\`\`"
