#!/usr/bin/lua

--
-- Author      : Andrei Dumitrescu <andrei@codemachiner.com>
-- Dep packages: [ pamixer ]
-- License     : MIT
-- Link        : github.com/andreid/dotfiles/.scripts/i3b__volume
--

package.path = package.path .. ";" .. os.getenv("HOME") .. "/.scripts/?.lua"
require( "common" ) -- import `os.run`

VOL = tonumber( arg[2] )
COMMAND = arg[1]
SIGN = COMMAND == "down" and "-d" or "-i"

if (COMMAND == "toggle") then
    os.execute( "pamixer --allow-boost -t" )
else
    os.execute( "pamixer --allow-boost " .. SIGN .. " " .. VOL )
end

VOLUME = os.run( "pamixer --get-volume" )
IS_MUTE = os.run( "pamixer --get-mute" ) == "true"

NOTIFY_MSG = "'<u>" .. (IS_MUTE and "Muted" or "Active") .. "</u> speaker volume is set to " .. VOLUME .. "%'"

os.execute( "notify-send -i -a '~/.scripts/cm_vol' -t 1000 " .. NOTIFY_MSG )

-- notify i3blocks to refresh all commands listening to signal 10
os.execute( "pkill -RTMIN+10 i3blocks" )
