#!/bin/sh

choices="Laptop|Laptop + HDMI1|Laptop + HDMI2|HDMI1|HDMI2|Manual"

chosen=$(echo -e "$choices" | rofi -dmenu -lines 6 -sep '|')

case "$chosen" in
    "Laptop + HDMI1") xrandr --output HDMI-1 --auto --output eDP-1 --auto --right-of HDMI-1 ;;
	"Laptop + HDMI2") xrandr --output HDMI-2 --auto --output eDP-1 --auto --right-of HDMI-2 ;;
	Laptop) xrandr --output HDMI-1 --off --output HDMI-2 --off --output eDP-1 --auto ;;
	HDMI1) xrandr --output HDMI-1 --auto --output eDP-1 --off ;;
    HDMI2) xrandr --output HDMI-2 --auto --output eDP-1 --off ;;
	Manual) arandr ;;
esac

# Relaunch dunst
# Refresh nitrogen wallpaper
[ "$chosen" == "" ] || pkill dunst && nitrogen --restore
