#!/bin/sh

choices="Laptop + HDMI1\nLaptop + HDMI2\nLaptop\nHDMI1\nHDMI2\nManual"

chosen=$(echo -e "$choices" | dmenu -i)

case "$chosen" in
    "Laptop + HDMI1") xrandr --output HDMI-1 --auto --output eDP-1 --auto --right-of HDMI-1 ;;
	"Laptop + HDMI2") xrandr --output HDMI-2 --auto --output eDP-1 --auto --right-of HDMI-2 ;;
	Laptop) xrandr --output HDMI-1 --auto --output eDP-1 --off ;;
	HDMI1) xrandr --output HDMI-1 --auto --output eDP-1 --off ;;
    HDMI2) xrandr --output HDMI-2 --auto --output eDP-1 --off ;;
	Manual) arandr ;;
esac

# Relaunch polybar if there was a selection.
[ "$chosen" == "" ] || polybar_launch

