#!/bin/sh

# Possible displays
screensAll=$(xrandr -q | grep "connected")

# Connected displays
screensConnected=$(echo "$screensAll" | grep " connected" | awk '{print $1}')

# Select with rofi
screenSelected=$(echo -e "${screensConnected}\\nManual" | rofi -dmenu -lines 6 -sep '\n')

# Compute xrandr params to disable others
screensOther=$(echo "$screensConnected" | grep -x -v "$screenSelected")
paramsDisable=$(echo "$screensOther" | awk '{print "--output", $1, "--off"}' | tr '\n' ' ')

xrandr --output $screenSelected --auto --scale 1.0x1.0 $paramsDisable

if [ "$screenSelected" != "" ]; then
    # Restore wallpaper to resize based on screen size
    feh --bg-scale "$HOME/wall.png"

    # Restart dunst to ensure proper location on screen
    pkill dunst
fi
