#!/usr/bin/lua

--
-- Author      : Andrei Dumitrescu <andrei@codemachiner.com>
-- Dep packages: [ alsamixer, pamixer, ttf-fontawesome, st ]
-- License     : MIT
-- Link        : github.com/andreidcm/dotfiles/blob/master/.scripts/i3b__volume
--
-- See `.scripts/cm__vol` for actual volume logic. Same command is used when
-- changing volume from other sources (keyboard).
--

package.path = package.path .. ";" .. os.getenv("HOME") .. "/.scripts/?.lua"
require( "common" ) -- import `os.run`

--
-- treat mouse events
--
MOUSE_EVENT = tonumber( os.getenv( "BLOCK_BUTTON" ) )
if ( MOUSE_EVENT == 1 ) then
    -- left click
    os.execute( "st -e alsamixer" ) -- replace st with your terminal
elseif ( MOUSE_EVENT == 3 ) then
    -- right click
    os.execute( "cm__vol toggle" )
elseif ( MOUSE_EVENT == 4 ) then
    -- mouse wheel up
    os.execute( "cm__vol up 5" )
elseif ( MOUSE_EVENT == 5 ) then
    -- mouse wheel down
    os.execute( "cm__vol down 5" )
end

--
-- retrieve values after command ran
--
VOLUME = os.run( "pamixer --get-volume" )
IS_MUTE = os.run( "pamixer --get-mute" ) == "true"

if ( IS_MUTE ) then
    print( "[" .. VOLUME .. "%]" )
else
    print( "[" .. VOLUME .. "%]" )
end
