#!/bin/bash

# Check mouse event
case $BLOCK_BUTTON in
        3) amixer -q -D pulse sset Capture toggle ;;
        4) amixer -q -D pulse sset Capture 5%+ ;;
        5) amixer -q -D pulse sset Capture 5%- ;;
esac

volume=$(amixer sget Capture | grep -E 'Front Left: Capture' | awk '{print $(NF-1)}' | grep -Eo '[0-9]{1,}')
mute=$(amixer sget Capture | grep -E 'Front Left: Capture' | awk '{print $NF}' | grep -Eo '\w{2,3}')

if [ $mute = 'off' ]
then
        echo "...$volume%";
        # exit 33;
else
        echo "...$volume%";
fi

