#!/usr/bin/lua

--
-- Author      : Andrei Dumitrescu <andrei@codemachiner.com>
-- Dep packages: [ mpstat, awk, htop ]
-- License     : MIT
-- Link        : github.com/andreid/dotfiles/.scripts/i3b__cpu
--

package.path = package.path .. ";" .. os.getenv("HOME") .. "/.scripts/?.lua"
require( "common" ) -- import `os.run`

--
-- retrieve each cpu load
--
CPU_LOAD = os.run( "mpstat -P ALL 1 1 | awk '/Average:/ && $2 ~ /[0-9]/ {print $3}'" )
CPUS = ""

-- cpus load are on separate lines
CPU_LOAD:gsub( "[^%c]+%c?", function ( cpu )
    -- one char for each core
    CPU_LOAD_TENS = math.floor( tonumber( cpu ) / 10 )
    CPUS = CPUS .. CPU_LOAD_TENS
end )

io.write( "["..CPUS.."]" )

--
-- treat mouse events
--
MOUSE_EVENT = tonumber( os.getenv( "BLOCK_BUTTON" ) )
if ( MOUSE_EVENT == 1 ) then
    -- left click
    os.execute( "st -e htop" )
end

os.exit()
