#!/usr/bin/perl

##
## Author      : Andrei Dumitrescu <andrei@codemachiner.com>
## Date        : 2nd July 2018
## Dep packages: [cat, head, grep]
## License     : MIT
## Link        : github.com/andreid/dotfiles/.scripts/i3b-memory
##

# sys command to get mem info
@memInfo = split( '\n', `cat /proc/meminfo | head -n 2 | grep -Eo '[0-9]{1,}'` );

$GB = 1024*1024;
$totalGB = sprintf( "%.2f", $memInfo[0] / $GB );
$usedGB = sprintf( "%.2f", ($memInfo[0] - $memInfo[1]) / $GB );

# i3block content
print( "$usedGB/$totalGB GB" );

# red background when using too much memory
if ($usedGB > $totalGB * 0.7) {
	exit 33;
}
