#!/bin/bash

case $BLOCK_BUTTON in
	1) $TERMINAL -e alsamixer ;;
	3) amixer -q -D pulse sset Master toggle ;;
	4) amixer -q -D pulse sset Master 5%+ ;;
	5) amixer -q -D pulse sset Master 5%- ;;
esac

volume=$(pamixer --get-volume)%
mute=$(pamixer --get-mute)

if [ $mute = true ]
then
	echo " ✕ VOL $volume ";
	exit 33;
else
	echo " ✓ VOL $volume ";
fi
