#!/bin/bash

##
## Author      : Andrei Dumitrescu <andrei@codemachiner.com>
## Dep packages: [ pamixer ]
## License     : MIT
## Link        : github.com/andreid/dotfiles/.scripts/lemmon_vol
##

result=$(date "+%A %T on %B %d")

echo -e $result
