#!/bin/bash

##
## Author      : Andrei Dumitrescu <andrei@codemachiner.com>
## License     : MIT
## Link        : github.com/andreid/dotfiles/.scripts/lemmon__index
##

sep="%{F$WHITED} // %{F-}"

while true; do
    VOL=%{F$YELLOW}$(lemon__vol)%{F-}
    MIC=%{F$YELLOW}$(lemon__mic)%{F-}
    DATE=$(lemon__date)
    WORKSPACES=$(lemon__workspaces)

    echo -e "${l} ${WORKSPACES} %{c}${DATE} %{r}${MIC}${sep}${VOL} "
    sleep 1
done
