#!/bin/sh

# Menu options.
item_snippets=" Snippets"
item_bookmarks=" Bookmarks"
item_color_picker=" Pick color"
item_openai_model="$OPENAI_ICON OpenAI - Change model"
item_openai_history="$OPENAI_ICON OpenAI - History"
item_nvim="$NVIM_ICON Neovim - Change config"
# item_projects=" Projects"
# item_power=" Power"

# Prepare menu items with shortcuts.
menu=$(cat << EOF
$item_openai_model
$item_openai_history
$item_nvim
$item_snippets <small>[ + s]</small>
$item_bookmarks <small>[ + b]</small>
$item_color_picker
EOF
)

choice=$(echo "$menu" | rofi -markup-rows -dmenu -p " ")

case "$choice" in
  "$item_openai_model"*) ai-model change ;;
  "$item_openai_history"*) terminal-center ai-history ;;
  "$item_nvim"*) nvim-config change ;;
  "$item_snippets"*) terminal-center snippets copy ;;
  "$item_bookmarks"*) terminal-center bookmarks open ;;
  "$item_color_picker"*) screenshot pick-color ;;
  # "$item_projects"*) projects.find ;;
  # "$item_power"*) rofi_power ;;
  *) echo "No valid option selected"; exit 1 ;;
esac
