#!/usr/bin/env dash

# ╭───┤ Input variables
# ╰─
prev_note_path="${HOME}/.jot/last_note_path"
should_continue=false

# ╭───┤ Parse flags 
# ╰─
while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      man --pager cat "$(dirname "$0")/jot.1"
      exit 0
    ;;
    -c|--continue)
      should_continue=true
      shift
    ;;
    --) shift; break ;;
    -?*) echo "error: unknown flag: $1" >&2; exit 1 ;;
    *) break ;;
  esac
done

# ╭──────────────────────
# │ Main. Start here.
# ╰────────

[ ! -d "${HOME}/.jot" ] && mkdir "${HOME}/.jot"

# Decide on the tmp file to edit.
# Either the last one, from a previous jot, or create a new one.
if [ "$should_continue" = true ] && [ -f "$prev_note_path" ]; then
  tmp_file=$(cat "$prev_note_path" 2>/dev/null)
fi

if [ -z "$tmp_file" ]; then
  tmp_file=$(mktemp /tmp/jot.XXXXXX)
fi

# Open Nvim, in edit mode, inside a alacritty terminal window. The class is
# used to center the window on the screen and is configured by the window
# manager, i3 in this case.
alacritty --title "Jot It Down - $tmp_file" \
  --class "center-float" \
  --command nvim \
    -c "setlocal syntax=markdown" \
    -c "setlocal wrap" \
    -c "setlocal spell" \
    -c "startinsert" \
    "$tmp_file"

# Persist the note for next time
text=$(cat "$tmp_file")
if [ -n "$text" ]; then
  printf "%s" "$text"
  echo "$tmp_file" > "$prev_note_path"
else
  echo "error: no text was entered" >&2
  exit 1
fi
