#!/usr/bin/env dash

# -e: exit on error, -u: error on undefined variable
set -eu 

# NAME
#  md-syntax - Determine markdown syntax for a file
#
# SYNOPSIS
#  md-syntax FILE_PATH
#
# DESCRIPTION
#  Determines the appropriate Markdown syntax for the given file based on its
#  file type and extension.
#
# SEE ALSO
#  file(1), head(1), realpath(1)

get_syntax_from_shebang() {
  shebang=$(head -n 1 "$1")

  case "$shebang" in
    "#!"*"bash"*) echo "bash" ;;
    "#!"*"zsh"*) echo "zsh" ;;
    '#!'*) echo "shell" ;;
    *) echo "plaintext" ;;
  esac
}

get_syntax() {
  path="$1"
  type=$(file --brief --mime-type "$path")

  case "$type" in
    "text/x-shellscript")
      get_syntax_from_shebang "$path"
    ;;
    "text/plain")
      case "$path" in
        *.py) echo "python" ;;
        *.js) echo "javascript" ;;
        *.jsx) echo "jsx" ;;
        *.ts) echo "typescript" ;;
        *.tsx) echo "tsx" ;;
        *.html) echo "html" ;;
        *.css) echo "css" ;;
        *.md) echo "markdown" ;;
        *.mdx) echo "mdx" ;;
        *.json) echo "json" ;;
        *.xml) echo "xml" ;;
        *.yml | *.yaml) echo "yaml" ;;
        *) get_syntax_from_shebang "$path" ;;
      esac
    ;;
    *) echo "plaintext" ;;
  esac
}

## 
## Main
##

if [ ! -f "$1" ]; then
  echo "File does not exist \"$1\"" >&2
  exit 1
fi

get_syntax "$1"

