#!/usr/bin/env sh

. "$CORE_LIBS/die"
. "$CORE_LIBS/stdin-or"
. "$CORE_LIBS/does-command-exist"

# NAME
#  yank - Display manager aware copy to clipboard, yank, script
#
# SYNOPSIS
#  yank [INPUT]...
#  echo [INPUT]... | yank
#
# DESCRIPTION
#  Copies the given input, arguments or piped input, to the clipboard. If
#  "wl-copy" is available, it is used, indicating a Wayland display. Otherwise,
#  "xsel" is used, indicating an X11 display. If neither is available, an error 
#  is thrown.
#
# SEE ALSO
#  wl-copy(1), xsel(1)

input=$(stdin_or "$@")

echo "input: $input"

# Wayland 
if does_command_exist "wl-copy" -eq 0; then
  wl-copy "$input"
  exit
fi

# X11
if does_command_exist "xsel" -eq 0; then
  printf "%b" "$input" | xsel --primary --input 
  printf "%b" "$input" | xsel --clipboard --input 
  exit
fi

die "Neither <u>wl-copy</u> nor <u>xsel</u> is available."

